// Defect register for the Risk Assessment Workbench test campaign. Test cases link here via the
// `tc.defect` annotation (lib/harness.ts -> defect()); the report builder joins the two and flags
// any defect whose linked tests all passed on this run (i.e. fixed / not reproduced).
//
// Severity: Critical = governance/security control is bypassable; High = acceptance criterion
// broken on the main path; Medium = AC partially met / wrong error semantics; Low = cosmetic/minor.

export const DEFECTS = [
  {
    id: 'DEF-001', severity: 'Critical', area: 'Assessment / Finalize (Epic 6)', stories: 'US-6.3, US-8.1, CLAUDE.md "no AI output reaches committee without a review gate"',
    title: 'Readiness gate passes vacuously - an assessment with nothing mapped, reviewed or scored can be finalized and routed to committee',
    actual: 'GET /Readiness returns isReady=true for a brand-new assessment with zero categories; Finalize and Route both return 200 and the item appears in the committee queue. The UI Finalize tab says "Ready to finalize." with the button enabled.',
    expected: 'Readiness requires at least one mapped category, a reviewed narrative and a score per category; finalize/route are refused otherwise.',
    rootCause: 'AssessmentService.CheckReadinessAsync only loops over active categories - with none, both outstanding lists are empty so IsReady is true.',
    fix: 'Treat "no active categories" (and "category without a score") as outstanding items; add a DB-level check in func_finalizeAssessment as well.',
  },
  {
    id: 'DEF-002', severity: 'Critical', area: 'Authorization (all modules)', stories: 'US-6.3 AC3, US-8.2, US-10.1, NFR-SEC',
    title: 'No server-side role enforcement; acting user is taken from the request body',
    actual: 'A Product Owner id is accepted as committeeMemberUserId (vote recorded and counted toward quorum -> decision "Deferred"), as the finalizing analyst, and as the author of a scoring-config change. Menu hiding is the only role restriction.',
    expected: '403 for actions outside the caller\'s role; the actor is derived from the authenticated token, never from the payload.',
    rootCause: 'Controllers accept ActorUserId / CommitteeMemberUserId / DecidedByUserId in DTOs and have no role/policy checks ([Authorize] only).',
    fix: 'Resolve the user from the JWT subject, add role policies per endpoint, and validate committee membership before counting a vote.',
  },
  {
    id: 'DEF-010', severity: 'Critical', area: 'Deployment / Authentication', stories: 'NFR-SEC, CLAUDE.md production readiness',
    title: 'Deployed Container App runs in Development mode with the auth bypass active',
    actual: 'Every API answers anonymous callers (user e-mails, all requests, config); a forged "alg:none" bearer token is accepted; /openapi/v1.json publishes all 45 routes; the SPA offers "Continue without signing in (local dev only)".',
    expected: 'Auth0 JWT validation on the public URL; OpenAPI and dev bypass disabled outside local dev.',
    rootCause: 'Container App has ASPNETCORE_ENVIRONMENT=Development and AUTH0_DOMAIN unset, so Program.cs registers DevBypassAuthHandler and MapOpenApi; the SPA was built without VITE_AUTH0_* values.',
    fix: 'Set ASPNETCORE_ENVIRONMENT=Production (or Staging) plus AUTH0_DOMAIN/AUTH0_AUDIENCE on the Container App; build the SPA with the Auth0 env vars; restrict ingress until then.',
  },
  {
    id: 'DEF-019', severity: 'High', area: 'Security / CORS', stories: 'NFR-SEC',
    title: 'CORS reflects any Origin',
    actual: 'GET and pre-flight requests from Origin https://evil.example receive Access-Control-Allow-Origin: https://evil.example.',
    expected: 'Only the deployed webapp origin is allowed (the SPA is same-origin, so none is needed at all).',
    rootCause: 'Likely an allow-all CORS policy on the Container App ingress or a wildcard CORS_ALLOWED_ORIGINS value (ops/README documents localhost only).',
    fix: 'Remove the ingress CORS policy / set CORS_ALLOWED_ORIGINS to the app\'s own origin.',
  },
  {
    id: 'DEF-003', severity: 'High', area: 'Committee voting (Epic 8)', stories: 'US-8.2 AC5, US-9.2',
    title: 'A committee member\'s vote is silently overwritten when they vote again',
    actual: 'Second vote by the same member returns 200 with the SAME vote id; the votes table now shows only the new vote (Approve -> Reject).',
    expected: 'Re-vote rejected (409), or a new versioned vote row with the original kept.',
    rootCause: 'func_castCommitteeVote uses ON CONFLICT (assessment_id, committee_member_user_id) DO UPDATE.',
    fix: 'Insert-only votes (reject duplicates) or append a new version and keep history; audit before/after.',
  },
  {
    id: 'DEF-030', severity: 'High', area: 'Committee voting (Epic 8)', stories: 'US-8.2 AC2-AC4',
    title: 'API accepts blank conditions / whitespace-only rationale',
    actual: 'ApproveWithConditions with conditionsText "" -> 200; Defer with rationale "   " -> 200. Only the UI validates.',
    expected: '400 - conditions / rationale must contain text.',
    rootCause: 'CHECK constraints test only IS NOT NULL; service does not trim/validate.',
    fix: 'Validate non-blank (trimmed) in CommitteeService and tighten the CHECK to length(trim(x)) > 0.',
  },
  {
    id: 'DEF-007', severity: 'High', area: 'Assessment lock (Epic 6)', stories: 'US-6.3 AC2',
    title: 'Finalized assessment is not locked - narrative, score and category edits still succeed',
    actual: 'After Finalize (and even after routing), Narrative/Edit, Scoring/Override and CategoryMapping/Override all return 200; UI keeps every editing control enabled.',
    expected: 'Writes to a Finalized assessment rejected (409) and controls disabled in the UI.',
    rootCause: 'No status guard in the Narrative / Scoring / CategoryMapping services or their stored functions.',
    fix: 'Guard every write path on assessment.status <> Finalized (DB function + service) and disable controls in AssessmentWorkspace.jsx.',
  },
  {
    id: 'DEF-008', severity: 'High', area: 'Intake / attachments (Epic 1)', stories: 'US-1.2 AC2',
    title: 'Replacing a document (new version) always fails with HTTP 500',
    actual: 'AttachDocumentFile and AttachDocument with supersedesAttachmentId both return 500 "Failed to attach document."; only version 1 rows can ever be created.',
    expected: 'Version 2 created; version 1 retained and marked superseded.',
    rootCause: 'Probable: func_attachDocument RETURNS TABLE (id, version_number), whose OUT columns shadow the table columns, making "UPDATE change_request_attachment ... WHERE id = ..." ambiguous in PL/pgSQL.',
    fix: 'Qualify the columns (a.id) or rename the OUT params; add a test for the replacement path.',
  },
  {
    id: 'DEF-020', severity: 'High', area: 'Document extraction UI (Epic 4)', stories: 'US-4.1',
    title: 'UI "Extract with AI" sends the file NAME as the document text - nothing is extracted',
    actual: 'Clicking Extract with AI on vendor-due-diligence.pdf shows "Extraction complete" but "Nothing extracted yet."; the same document text sent via the API extracts vendor, jurisdiction (Malta), data scope, etc.',
    expected: 'Extraction runs on the server-side extracted text of the attachment.',
    rootCause: 'webapp/src/pages/AssessmentWorkspace.jsx ExtractionTab posts documentText: attachment.fileName.',
    fix: 'Let the API load change_request_attachment.extracted_text by attachmentId (drop documentText from the client contract).',
  },
  {
    id: 'DEF-033', severity: 'High', area: 'Extraction UI (Epic 4)', stories: 'US-4.2',
    title: 'Correcting an extracted field from the UI always fails',
    actual: 'Clicking Correct shows "Failed to correct extracted field." (HTTP 500); the field keeps its AI value. The same correction through the API with an actorUserId succeeds (TC-API-051).',
    expected: 'Correction saved; original AI value retained in the audit trail.',
    rootCause: 'ExtractionTab.correct() in AssessmentWorkspace.jsx omits actorUserId from input, so Guid.Empty is written and fails the actor foreign key.',
    fix: 'Send currentUser.id (better: take the actor from the token server-side, see DEF-002) and map the FK failure to 400.',
  },
  {
    id: 'DEF-016', severity: 'High', area: 'Scoring configuration (Epic 10)', stories: 'US-10.1 AC1',
    title: 'Scoring-config changes apply to in-flight assessments',
    actual: 'An assessment opened while the cap was 0.85 was scored with 0.80 immediately after the cap was changed.',
    expected: 'In-flight assessments keep the configuration version in force when they started unless explicitly re-run.',
    rootCause: 'func_calculateAndSaveRiskScore reads the currently active scoring_config instead of the version pinned on the assessment (fk_assessment_scoring_config_version exists but is unused).',
    fix: 'Pin the config version at OpenWorkspace and read that version during calculation.',
  },
  {
    id: 'DEF-021', severity: 'High', area: 'Committee UI (Epic 8)', stories: 'US-8.2 AC1, US-8.1 AC1',
    title: 'Committee vote panel does not show the assessment being voted on',
    actual: 'The Review panel shows only request number/title, the vote form and the vote list - no narrative, scores, cited policy or override history.',
    expected: 'Full read-only assessment (narrative, scores, cited policy, analyst overrides) visible before voting.',
    rootCause: 'CommitteeQueue.jsx VotePanel renders no assessment content.',
    fix: 'Render a read-only assessment summary (reuse the workspace data endpoints) above the vote form.',
  },
  {
    id: 'DEF-006', severity: 'High', area: 'Intake / attachments (Epic 1)', stories: 'US-1.2 AC1, NFR-SEC',
    title: 'Upload type check trusts the client Content-Type; rejections return 500',
    actual: 'malicious.exe uploaded as application/pdf is accepted (200). .txt and .exe with their real types return 500 "Failed to attach document." instead of a clear 400 naming the allowed formats; the UI shows the same generic toast.',
    expected: 'Type validated by extension + magic bytes; clear 400 "Allowed: PDF, DOCX, XLSX".',
    rootCause: 'ChangeRequestService checks only the supplied Content-Type; its InvalidOperationException is not caught by the controller.',
    fix: 'Sniff file signatures, check extension, and map validation exceptions to 400.',
  },
  {
    id: 'DEF-005', severity: 'Medium', area: 'API error handling (cross-cutting)', stories: 'NFR, US-1.1, US-3.2, US-7.1, US-10.1, US-10.2',
    title: 'Validation failures surface as HTTP 500 with a generic message',
    actual: 'Unknown/empty change type, reliance decision "Maybe", inherent 0/6 or effectiveness 1.5/-0.2, workflow value "{not json", blank scoring-config reason and unsupported uploads all return 500 "Failed to ...". The UI then shows e.g. "Failed to calculate risk score."',
    expected: '400 with a message saying what is wrong.',
    rootCause: 'BaseApiController only converts service-level InvalidOperationExceptions caught in specific controllers; PostgresException from CHECK/RAISE bubbles to the generic 500.',
    fix: 'Validate inputs in the services (or FluentValidation) and map PostgresException 23514/P0001 to 400 centrally.',
  },
  {
    id: 'DEF-009', severity: 'Medium', area: 'Intake (Epic 1)', stories: 'US-1.1 AC3, NFR-SEC',
    title: 'No server-side validation of mandatory fields or field length',
    actual: 'A request with empty title and description is created (200, new CR number); a 20,000-character title is accepted.',
    expected: '400 listing the missing fields; bounded lengths.',
    rootCause: 'SubmitChangeRequestInput has no validation; only the SPA checks.',
    fix: 'Add [Required]/[MaxLength] or explicit checks in ChangeRequestService.',
  },
  {
    id: 'DEF-011', severity: 'Medium', area: 'Policy research (Epic 3)', stories: 'US-3.2, US-9.1',
    title: 'Relying on the same passage for a second category discards the decision',
    actual: 'RecordReliance for chunk X under Customers & Entities then Delivery Channels returns the SAME id; only the first category keeps the row, so the second category still shows "No policy reviewed".',
    expected: 'One reliance row per (assessment, category, passage).',
    rootCause: 'func_recordPolicyReliance ON CONFLICT (assessment_id, policy_chunk_id) - risk_category_id is not in the key.',
    fix: 'Include risk_category_id in the unique key.',
  },
  {
    id: 'DEF-012', severity: 'Medium', area: 'AI category mapping (Epic 2)', stories: 'US-2.1, CLAUDE.md change-type mapping',
    title: 'AI category proposal is inconsistent - Vendor onboarding sometimes omits Delivery Channels',
    actual: 'Across runs the same kind of Vendor request was mapped to Customers & Entities only (API lifecycle, 3 of 3 runs) and to Customers & Entities + Delivery Channels (UI, final run). The primary mapping is left to the model.',
    expected: 'Vendor onboarding -> Customers & Entities + Delivery Channels (the documented primary mapping).',
    rootCause: 'The deterministic change-type -> category baseline is not enforced; the proposal is left entirely to the model.',
    fix: 'Seed the primary categories deterministically and let the model add/justify extras (and add an eval case).',
  },
  {
    id: 'DEF-013', severity: 'Medium', area: 'Scoring (Epic 7)', stories: 'US-7.1 AC3',
    title: 'Controls library is empty, so credited controls cannot be traced',
    actual: 'GET /Scoring/Controls/{id} returns 0 controls for all four categories; the UI always sends controlIdsCredited: [].',
    expected: 'A seeded controls library per category with configured mitigation weights, selectable in the Scoring tab.',
    rootCause: 'No seed data for controls; no control picker in the UI.',
    fix: 'Seed synthetic controls and add a multi-select to ScoringTab.',
  },
  {
    id: 'DEF-022', severity: 'Medium', area: 'Decision outcome / notifications (Epics 1, 8)', stories: 'US-8.3 AC1-AC3, US-1.3 AC2',
    title: 'Requester sees "Decisioned" only - no decision, conditions or notifications',
    actual: 'After an Approved-with-Conditions decision, My Requests shows status "Decisioned"; the outcome and conditions are not visible to the Product Owner and no notification exists.',
    expected: 'Request status Approved / Rejected / Deferred / Approved-with-Conditions with the conditions attached; PO notified.',
    rootCause: 'change_request.status is set to the generic Decisioned; MyRequests.jsx has no decision view; notifications not implemented.',
    fix: 'Store the resolution on the request, show it (with conditions) on My Requests, add in-app notifications.',
  },
  {
    id: 'DEF-024', severity: 'Medium', area: 'Intake UI (Epic 1)', stories: 'US-1.1 AC2',
    title: 'No structured type-specific fields per change type',
    actual: 'Vendor and Geography show the same single free-text "Type-specific details" box; no vendor name / jurisdiction / data-scope or target country fields.',
    expected: 'Structured, mandatory fields per change type.',
    rootCause: 'Intake.jsx renders one generic textarea.',
    fix: 'Define a per-type field schema and render/validate it (client + server).',
  },
  {
    id: 'DEF-026', severity: 'Medium', area: 'Policy research UI (Epic 3)', stories: 'US-3.1 AC1-AC2',
    title: 'Policy results show no source link, effective date or relevance rationale',
    actual: 'Each result shows section reference and passage text only, although the API returns sourceUrl and effectiveDate.',
    expected: 'Link to the source document, version/effective date, and why it was ranked.',
    rootCause: 'PolicyTab renders only sectionRef and chunkText.',
    fix: 'Render documentTitle, sourceUrl (link), effectiveDate and rank/rationale.',
  },
  {
    id: 'DEF-027', severity: 'Medium', area: 'Extraction UI (Epic 4 / 6)', stories: 'US-4.2 AC1, US-6.1 AC1',
    title: 'Extracted-field correction has no reason input',
    actual: 'The Correct button always sends reason "Analyst correction" and isMaterialChange=true; the analyst cannot state why.',
    expected: 'Analyst enters a reason for material corrections (mandatory), optional for formatting fixes.',
    rootCause: 'Hard-coded values in ExtractionTab.correct().',
    fix: 'Add a reason field and a "material change" toggle.',
  },
  {
    id: 'DEF-028', severity: 'Medium', area: 'Audit (Epic 9)', stories: 'US-6.2 AC2, US-9.1 AC3',
    title: 'Examiner export of the audit trail',
    actual: 'Initial run found no export control in the repository source. The deployed build does provide "Export PDF" (verified: valid PDF downloaded). On-screen entries still show action/actor/reason without before/after values.',
    expected: 'Durable, human-readable export with before/after state per entry.',
    rootCause: 'Not implemented.',
    fix: 'Add a server-side PDF/CSV export of GET /Audit/{id} including before/after JSON.',
  },
  {
    id: 'DEF-032', severity: 'Medium', area: 'Policy corpus / RAG (Epic 3)', stories: 'US-3.1, CLAUDE.md data strategy #2',
    title: 'Policy corpus has 5 passages - most core FFIEC topics return nothing',
    actual: 'Only 5 passages exist in total; wire transfer, correspondent banking, PEP, sanctions, MSB and other core topics return no match.',
    expected: 'A corpus covering the FFIEC / FATF sections the four categories cite.',
    rootCause: 'Seed corpus is a placeholder.',
    fix: 'Ingest the FFIEC BSA/AML manual sections + FATF lists (chunk + index) as planned.',
  },
  {
    id: 'DEF-017', severity: 'Medium', area: 'Security headers', stories: 'NFR-SEC',
    title: 'Missing security headers; server banner disclosed',
    actual: 'No Strict-Transport-Security, Content-Security-Policy, X-Content-Type-Options, X-Frame-Options or Referrer-Policy; "Server: Kestrel".',
    expected: 'Standard hardening headers present; banner removed.',
    rootCause: 'No header middleware; Kestrel AddServerHeader default.',
    fix: 'Add a security-headers middleware and KestrelServerOptions.AddServerHeader = false.',
  },
  {
    id: 'DEF-029', severity: 'Medium', area: 'Accessibility', stories: 'NFR-A11Y',
    title: 'WCAG 2.1 AA violations on most screens (see axe evidence per screen)',
    actual: 'axe-core: button-name [critical] on every signed-in screen (icon-only buttons such as the mobile menu / sidebar close and the select triggers have no accessible name); label [critical] x4 on Configuration (Rule key, Reason, Value, Category not associated); color-contrast [serious] x7 in the workspace (muted text); scrollable-region-focusable [serious] on My Requests.',
    expected: 'No critical/serious violations.',
    rootCause: 'See evidence - typically colour contrast and form controls without programmatic labels (<Label> without htmlFor on selects/inputs).',
    fix: 'Associate labels (htmlFor/aria-labelledby), fix contrast tokens, add accessible names.',
  },
  {
    id: 'DEF-014', severity: 'Low', area: 'Scoring (Epic 7)', stories: 'US-7.2',
    title: 'Overridden score still attributed to "System"',
    actual: 'After an analyst override the score row has isOverride=true but scoredBy="System".',
    expected: 'scoredBy = "Analyst" (and the analyst id) for overrides.',
    rootCause: 'func_overrideRiskScore does not update scored_by.',
    fix: 'Set scored_by = \'Analyst\' in the override function.',
  },
  {
    id: 'DEF-018', severity: 'Low', area: 'API error messages', stories: 'NFR-SEC',
    title: 'Database error codes leak into user-facing messages',
    actual: 'e.g. "P0001: A reason is required to edit an AI-drafted narrative section".',
    expected: 'Clean domain message without PostgreSQL SQLSTATE codes.',
    rootCause: 'PostgresException.Message passed through.',
    fix: 'Use PostgresException.MessageText or map to domain messages.',
  },
  {
    id: 'DEF-023', severity: 'Low', area: 'Intake UI (Epic 1)', stories: 'US-1.1 AC3',
    title: 'Missing-field message does not list which fields are missing',
    actual: 'Always "Change type, title, and description are required." even when only one is missing; no inline field errors.',
    expected: 'Message / inline errors naming only the missing fields.',
    rootCause: 'Single static toast in Intake.jsx.',
    fix: 'Compute the missing list; add aria-invalid + inline messages.',
  },
  {
    id: 'DEF-031', severity: 'Low', area: 'Performance', stories: 'NFR-PERF',
    title: 'Unpaginated request list is slow; large JS bundle',
    actual: 'GET /api/ChangeRequest p95 ~2.4 s (grows with every request - no paging); DOMContentLoaded ~2.4 s; ~650 KB JS.',
    expected: 'p95 < 1.5 s for reads; paged lists; code-split bundle.',
    rootCause: 'func_getAllChangeRequests returns every row; single Vite chunk.',
    fix: 'Add paging/filters; lazy-load pages.',
  },
  {
    id: 'DEF-025', severity: 'Low', area: 'UI shell', stories: 'NFR-UX',
    title: 'User switcher truncates the role ("ProductOwne")',
    actual: 'Header switcher reads "Priya Owens — ProductOwne" at 1440 px.',
    expected: 'Full label or ellipsis with a tooltip.',
    rootCause: 'Fixed w-56 trigger.',
    fix: 'Widen / add truncate + title.',
  },
]
