/**
 * The six synthetic users from seed/seed_dev_users.sql, fetched by role rather than hardcoded by
 * id - ids are generated by the seed script, so pinning them here would break on any re-seed.
 *
 * Roles: ProductOwner | Analyst | CommitteeMember | Admin (see Models/Users/AppUser.cs).
 */
export async function usersByRole(request) {
  const response = await request.get('/api/User');

  if (!response.ok()) {
    throw new Error(
      `GET /api/User returned ${response.status()} - cannot resolve seeded users. ` +
        `Has ops/setup-local-db.sh been run against this database?`,
    );
  }

  const body = await response.json();
  const users = body.data ?? body.Data ?? [];

  if (users.length === 0) {
    throw new Error('GET /api/User returned no users - the app_user table looks unseeded.');
  }

  const byRole = (role) => users.find((user) => (user.role ?? user.Role) === role);

  return {
    all: users,
    productOwner: byRole('ProductOwner'),
    analyst: byRole('Analyst'),
    committeeMember: byRole('CommitteeMember'),
    admin: byRole('Admin'),
  };
}

/** Any well-formed GUID that is deliberately not a real record - for probes that must be rejected
 *  on authorization grounds BEFORE any database lookup happens. */
export const NON_EXISTENT_ID = '00000000-0000-0000-0000-0000000000ff';
